### ISSUE TITLE
Setting PPQ value

### ISSUE THREAD

**Issue by kwonyounggu** [abudaan/qambi#1]
Thank you very much for your great works on the qambi.
Now I am testing with my midi file having ppq, 384 and found that the ppq value changed to 960.
Is there any way to unchange or change back the original ppq value ?
Looking forward to hearing from you.

**Comment by abudaan** [comment]
Thanks! 960 is the default ppq value, you can set it to another value by adding ppq to the settings object that you pass to the Song constructor:

```javascript
const mySong = new Song({
   ppq: 384,
});
```
See also the rudimentary [wiki](https://github.com/abudaan/qambi/wiki/Song)

**Comment by kwonyounggu** [comment]
Thank you very much for your helpful information, Daniel.
